[package]
name = "rtss-rs"
version = "0.1.0"
edition = "2024"
[dependencies]
rtss-sys = { git = "https://github.com/ShayBox/RTSS-SYS", version = "0.1.2" }
rust-ini = "0.21.3"
windows = { version = "0.61.3", features = ["Win32", "Win32_System","Win32_System_Memory"] }
